### ISSUE TITLE
Qperson

### ISSUE THREAD

**Issue by rajayogadharasan** [pkainulainen/spring-data-jpa-examples#2]
Where is Qperson modal occurring error

**Comment by paulvi** [comment]
Where is error ?

**Comment by pkainulainen** [comment]
Closing this one since I don't know what is wrong.

**Comment by shayanfazeli** [comment]
QPerson class which is used in this project does not exist.

**Comment by pkainulainen** [comment]
The QPerson class is a Querydsl query that is generated by the Maven APT Plugin. The configuration of this plugin is explained here: https://www.petrikainulainen.net/programming/spring-framework/spring-data-jpa-tutorial-part-five-querydsl/ - Also, the POM file of the example project contains the configuration of this plugin and these query types should be generated automatically.
