### ISSUE TITLE
CsrfHeaderFilter class name 

### ISSUE THREAD

**Issue by msaiducar** [pkainulainen/spring-data-jpa-examples#4]
The name of file CSRFHeaderFilter.java but in it, the class declaration, CsrfHeaderFilter is used. I couldn't compile&run query-method project. I renamed the file name CSRF.... to Csrf and it works.

**Comment by pkainulainen** [comment]
This should is fixed now. I am sorry that I didn't address this sooner but I didn't get any notification from Github. I guess it's time to check my notification settings. Thank you for reporting this.
